# Generated by Django 5.2.16 on 2026-07-12 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0003_remove_auditlog_common_audi_user_id_6139e3_idx_and_more"),
        ("drivers", "0003_remove_driver_driver_name_and_more"),
        ("trips", "0003_remove_trip_end_time_trip_actual_duration_and_more"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fuel_log_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, unique=True
                    ),
                ),
                ("fuel_station", models.CharField(blank=True, max_length=255)),
                ("fuel_vendor", models.CharField(blank=True, max_length=255)),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("PETROL", "Petrol"),
                            ("DIESEL", "Diesel"),
                            ("CNG", "CNG"),
                            ("ELECTRIC", "Electric"),
                            ("HYBRID", "Hybrid"),
                            ("OTHER", "Other"),
                        ],
                        default="DIESEL",
                        max_length=50,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Liters or KWh", max_digits=10
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "odometer_reading",
                    models.DecimalField(
                        decimal_places=2, help_text="Current Odometer", max_digits=10
                    ),
                ),
                (
                    "distance_since_last",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "fuel_efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Km/L or Km/KWh",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("UPI", "UPI"),
                            ("COMPANY_ACCOUNT", "Company Account"),
                        ],
                        default="CARD",
                        max_length=50,
                    ),
                ),
                ("invoice_number", models.CharField(blank=True, max_length=100)),
                (
                    "invoice_upload",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
                ("fuel_date", models.DateField(db_index=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="common.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_logs",
                        to="drivers.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_logs",
                        to="trips.trip",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "fuel_fuel_log",
                "ordering": ["-fuel_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["vehicle", "fuel_date"],
                        name="fuel_fuel_l_vehicle_11852d_idx",
                    )
                ],
            },
        ),
    ]
