# Generated by Django 5.2.16 on 2026-07-12 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="common_audi_user_id_6139e3_idx",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="browser",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="module",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
