# Generated by Django 5.2.16 on 2026-07-12 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_remove_auditlog_common_audi_user_id_6139e3_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="browser",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="module",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_logs",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["user", "module", "created_at"],
                name="common_audi_user_id_6139e3_idx",
            ),
        ),
    ]
