# Generated by Django 5.2.16 on 2026-07-12 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FuelLog",
        ),
    ]
