# Generated by Django 5.2.16 on 2026-07-12 05:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_remove_auditlog_common_audi_user_id_6139e3_idx_and_more"),
        ("drivers", "0003_remove_driver_driver_name_and_more"),
        ("expenses", "0003_delete_fuellog"),
        ("trips", "0003_remove_trip_end_time_trip_actual_duration_and_more"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"ordering": ["-expense_date", "-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="expense",
            name="expenses_ex_date_17a2b2_idx",
        ),
        migrations.RemoveIndex(
            model_name="expense",
            name="expenses_ex_vehicle_b987ce_idx",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="expense",
            name="date",
        ),
        migrations.AddField(
            model_name="expense",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="expense",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="drivers.driver",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="expense_date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="expense",
            name="expense_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, unique=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="expense",
            name="invoice_upload",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("CHEQUE", "Cheque"),
                    ("CREDIT_CARD", "Credit Card"),
                    ("DEBIT_CARD", "Debit Card"),
                    ("UPI", "UPI"),
                    ("COMPANY_WALLET", "Company Wallet"),
                ],
                default="BANK_TRANSFER",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="reference_number",
            field=models.CharField(
                blank=True, help_text="Transaction ID or Cheque No", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="expense",
            name="vendor",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="expense",
            name="vendor_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(
                choices=[
                    ("FUEL", "Fuel"),
                    ("MAINTENANCE", "Maintenance"),
                    ("PARKING", "Parking"),
                    ("TOLL", "Toll"),
                    ("INSURANCE", "Insurance"),
                    ("REPAIR", "Repair"),
                    ("SALARY", "Salary"),
                    ("FINE", "Fine"),
                    ("ACCIDENT", "Accident"),
                    ("CLEANING", "Cleaning"),
                    ("PERMIT", "Permit"),
                    ("TAX", "Tax"),
                    ("MISC", "Miscellaneous"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["status"], name="expenses_ex_status_cbb790_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["expense_date"], name="expenses_ex_expense_cf8a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["vehicle", "expense_date"],
                name="expenses_ex_vehicle_c43aef_idx",
            ),
        ),
    ]
