# Generated by Django 5.2.16 on 2026-07-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maintenancelog",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="maintenancelog",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="maintenancelog",
            name="invoice",
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="actual_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="actual_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="diagnosis",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="estimated_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="estimated_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="invoice_upload",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="maintenance_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, unique=True
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="mechanic_contact",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="mechanic_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="parts_used",
            field=models.TextField(blank=True, help_text="List of parts used"),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="warranty",
            field=models.CharField(
                blank=True, help_text="Warranty details", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="workshop",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="maintenancelog",
            name="status",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="maintenancetype",
            name="name",
            field=models.CharField(
                choices=[
                    ("OIL_CHANGE", "Oil Change"),
                    ("TYRE_REPLACEMENT", "Tyre Replacement"),
                    ("BRAKE_SERVICE", "Brake Service"),
                    ("ENGINE_REPAIR", "Engine Repair"),
                    ("BATTERY_REPLACEMENT", "Battery Replacement"),
                    ("CLUTCH", "Clutch"),
                    ("GEARBOX", "Gearbox"),
                    ("SUSPENSION", "Suspension"),
                    ("AC_SERVICE", "AC Service"),
                    ("ELECTRICAL", "Electrical"),
                    ("GENERAL_SERVICE", "General Service"),
                    ("ACCIDENT_REPAIR", "Accident Repair"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
