# Generated by Django 5.2.16 on 2026-07-12 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_auditlog_browser_alter_auditlog_action_and_more"),
        ("maintenance", "0003_remove_maintenancelog_cost_and_more"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancelog",
            name="maintenance_end",
            field=models.DateTimeField(
                blank=True,
                help_text="Exact datetime the vehicle is expected back (UTC).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="maintenancelog",
            name="maintenance_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Exact datetime the vehicle enters the workshop (UTC).",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancelog",
            index=models.Index(
                fields=["vehicle", "maintenance_start", "maintenance_end"],
                name="maintenance_vehicle_c9271e_idx",
            ),
        ),
    ]
