# Generated by Django 5.2.16 on 2026-07-12 04:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "license_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "license_category",
                    models.CharField(
                        choices=[
                            ("LMV", "Light Motor Vehicle"),
                            ("HMV", "Heavy Motor Vehicle"),
                            ("HGMV", "Heavy Goods Motor Vehicle"),
                            ("COMMERCIAL", "Commercial"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("license_expiry", models.DateField()),
                (
                    "document_url",
                    models.URLField(blank=True, max_length=1024, null=True),
                ),
            ],
            options={
                "db_table": "drivers_driver_license",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("driver_name", models.CharField(max_length=255)),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                ("phone", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                ("address", models.TextField()),
                ("joining_date", models.DateField()),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=0, help_text="Experience in years"
                    ),
                ),
                ("emergency_contact", models.CharField(max_length=100)),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "safety_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Score out of 100",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ON_TRIP", "On Trip"),
                            ("OFF_DUTY", "Off Duty"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("photo", models.URLField(blank=True, max_length=1024, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="common.company",
                    ),
                ),
            ],
            options={
                "db_table": "drivers_driver",
            },
        ),
    ]
