# Generated by Django 5.2.16 on 2026-07-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="driver",
            name="driver_name",
        ),
        migrations.RemoveField(
            model_name="driver",
            name="emergency_contact",
        ),
        migrations.AddField(
            model_name="driver",
            name="alt_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="driver",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="driver",
            name="driver_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, unique=True
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="driver",
            name="emergency_contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="driver",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="driver",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("OTHER", "Other")],
                default="MALE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="driver",
            name="medical_certificate_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="medical_certificate_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="driver",
            name="pincode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="driver",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="driver",
            name="salary",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="driver",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="driverlicense",
            name="license_authority",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="driverlicense",
            name="license_issue_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="license_category",
            field=models.CharField(
                choices=[
                    ("LMV", "Light Motor Vehicle"),
                    ("HMV", "Heavy Motor Vehicle"),
                    ("TRANSPORT", "Transport"),
                    ("HGMV", "Heavy Goods Motor Vehicle"),
                    ("PASSENGER", "Passenger"),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
