# Generated by Django 5.2.16 on 2026-07-12 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0003_remove_driver_driver_name_and_more"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="assigned_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_driver_set",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="driver",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
