# Generated by Django 5.2.16 on 2026-07-12 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "registration_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "vin_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("vehicle_name", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=100)),
                ("manufacturer", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                (
                    "maximum_load_capacity",
                    models.DecimalField(
                        decimal_places=2, help_text="Capacity in KGs", max_digits=10
                    ),
                ),
                (
                    "current_odometer",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("ELECTRIC", "Electric"),
                            ("CNG", "CNG"),
                            ("HYBRID", "Hybrid"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "acquisition_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("insurance_number", models.CharField(blank=True, max_length=100)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("fitness_expiry", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ON_TRIP", "On Trip"),
                            ("MAINTENANCE", "Maintenance"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("image", models.URLField(blank=True, max_length=1024, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="common.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="common.region",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vehicles_vehicle",
            },
        ),
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Registration Certificate"),
                            ("INSURANCE", "Insurance"),
                            ("FITNESS", "Fitness"),
                            ("PERMIT", "Permit"),
                            ("POLLUTION", "Pollution Certificate"),
                            ("INVOICE", "Invoice"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(max_length=1024)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
            options={
                "db_table": "vehicles_vehicle_document",
            },
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("TRUCK", "Truck"),
                            ("MINI_TRUCK", "Mini Truck"),
                            ("PICKUP", "Pickup"),
                            ("VAN", "Van"),
                            ("BUS", "Bus"),
                            ("TRAILER", "Trailer"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "vehicles_vehicle_type",
            },
        ),
        migrations.AddField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vehicles",
                to="vehicles.vehicletype",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["status", "region"], name="vehicles_ve_status_722ef4_idx"
            ),
        ),
    ]
