# Generated by Django 5.2.16 on 2026-07-12 04:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("old_status", models.CharField(max_length=50)),
                ("new_status", models.CharField(max_length=50)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "trips_trip_history",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "trip_number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("source", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                (
                    "cargo_weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in KGs", max_digits=10
                    ),
                ),
                ("cargo_type", models.CharField(max_length=100)),
                (
                    "planned_distance",
                    models.DecimalField(
                        decimal_places=2, help_text="Distance in KMs", max_digits=10
                    ),
                ),
                (
                    "actual_distance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "fuel_consumed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fuel in Liters",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "start_odometer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "end_odometer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("DISPATCHED", "Dispatched"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="common.company",
                    ),
                ),
            ],
            options={
                "db_table": "trips_trip",
            },
        ),
    ]
