# Generated by Django 5.2.16 on 2026-07-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
        ("trips", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="end_time",
        ),
        migrations.AddField(
            model_name="trip",
            name="actual_duration",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="arrival_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="cargo_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="customer_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="trip",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="trip",
            name="dispatch_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="estimated_duration",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Duration in Hours",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="intermediate_stops",
            field=models.TextField(
                blank=True, help_text="Comma separated list of stops"
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trips",
                to="common.region",
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cargo_weight",
            field=models.DecimalField(
                decimal_places=2, default=0.0, help_text="Weight in KGs", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="planned_distance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Distance in KMs",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("DISPATCHED", "Dispatched"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
