# Generated by Django 5.2.16 on 2026-07-12 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_auditlog_browser_alter_auditlog_action_and_more"),
        ("drivers", "0004_driver_assigned_vehicle_alter_driver_address_and_more"),
        ("trips", "0003_remove_trip_end_time_trip_actual_duration_and_more"),
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="actual_end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Actual end time recorded at completion.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="actual_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Actual start time recorded at dispatch.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="planned_end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Planned trip end (UTC). Used for collision detection.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="planned_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Planned trip start (UTC). Used for collision detection.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["planned_start_time"], name="trips_trip_planned_f12c47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["planned_end_time"], name="trips_trip_planned_cc1705_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["vehicle", "planned_start_time", "planned_end_time"],
                name="trips_trip_vehicle_4b0ff3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trip",
            index=models.Index(
                fields=["driver", "planned_start_time", "planned_end_time"],
                name="trips_trip_driver__1fae38_idx",
            ),
        ),
    ]
